name: Backend CD

on:
  push:
    branches:
      - main

jobs:
  detect-backend-changes:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if backend changed
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'

  deploy-backend:
    needs: detect-backend-changes
    if: needs.detect-backend-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X POST "${{ secrets.BACKEND_DEPLOY_HOOK }}"
