name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  # -------------------------
  # Detect which folder changed
  # -------------------------
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  # -------------------------
  # Backend CI
  # -------------------------
  backend-ci:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install
        run: npm ci

      - name: Lint (if exists)
        run: npm run lint --if-present

      - name: Test (if exists)
        run: npm test --if-present

  # -------------------------
  # Frontend CI
  # -------------------------
  frontend-ci:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

  # -------------------------
  # Deploy Backend (Render Hook)
  # -------------------------
  deploy-backend:
    needs: [changes, backend-ci]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        if: secrets.BACKEND_DEPLOY_HOOK != ''
        run: curl -X POST "${{ secrets.BACKEND_DEPLOY_HOOK }}"

